language: swift
osx_image: xcode9.4.1
script:
    - xcodebuild clean test -project socialFB.xcodeproj -scheme socialFB -destination "platform=iOS Simulator,name=iPhone 7,OS=11.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
